### ISSUE TITLE
VirusTotal Results

### ISSUE THREAD

**Issue by raymondyew** [Mightypotatoast/Video-Compressor-for-Discord#2]
It's only 1/62 Virus Scanners and I'm not saying this is a virus. But VirusTotal marks Transcord v1.2.2 as a Trojan.PSW.Stealer.cgk from "Jiangmin".

**Comment by raymondyew** [comment]
https://www.virustotal.com/gui/file/1b9610d08e08488492727a6cea96e96924ff671ee3d1445d034b6760c4c1ab1b
Here's the link ^^

**Comment by Mightypotatoast** [comment]
I think its because I modify a windows path to use the included FFMPEG executable, I don't plant to rework that tho so it will stay as it is until its broken.

if you want to be sure its not a virus you can check the code yourself its like 200l long and run it in a VM with python.
